component2("aki_grammar")
  kind("SharedLib")
  files({
    "*.cc",
    "*.h",
    "premake5.lua",
  })
  includedirs({
    "../utils",
  })
  defines("AKI_GRAMMAR_BUILD")
  dependencies({
    "fmtlib",
  })

unittest2("aki_grammar:grammar_tests")
  files({
    "*.cc",
    "*.h",
  })
  includedirs({
    "../utils",
  })
  dependencies({
    "fmtlib"
  })
  add_generic_test_main()