-- For more premake documentation, see https://premake.github.io/docs/

workspace "AkiPremakeDemo"
  location "build"
  language "C++"
  architecture "x86_64"
  filter { "configurations:Debug" }
    -- We want debug symbols in our debug config
	symbols "On"

  filter { "configurations:Release" }
	-- Release should be optimized
	optimize "On"

  -- Where to put the compiled files
  targetdir "bin/%{cfg.buildcfg}"

project "DemoApp"
  kind "ConsoleApp"
  files { "main.cc", "variables.aki" } -- include the aki files just as if they were cpp files
  includedirs { ".", "%{cfg.targetdir}" } -- include the targetdir as its where we dump the autogenerated aki
