
-- THE FOLLOWING IS A HACK SINCE WE CANT
-- PUT THE AKI TOOLING EXTENSION IN THE PROPER EXTENSION FOLDER HERE
-- >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
-- Get the absolute path to the script's directory
-- Get the project root directory (assuming we're in samples/tooling/build)
local scriptDir = debug.getinfo(1, "S").source:match[[^@?(.*[\/])[^\/]-$]]
if not scriptDir then scriptDir = "." end

-- Navigate up to the aki project root and then to the tooling directory
local toolingPath = path.join(scriptDir, "../../../tooling/build")
package.path = package.path .. ";" .. toolingPath .. "/?.lua"
-- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

-- For more premake documentation, see https://premake.github.io/docs/
-- Bring in the aki tooling extension (You may put it whereever you want)):
-- Make premake able to find the aki tooling extension
require "/premake5/aki"

workspace "AkiPremakeDemo"
  location "build"
  language "C++"
  architecture "x86_64"
  configurations({
    "Debug",
    "Release",
  })
  filter { "configurations:Debug" }
    -- We want debug symbols in our debug config
	symbols "On"

  filter { "configurations:Release" }
	-- Release should be optimized
	optimize "On"

  -- Where to put the compiled files
  targetdir "bin/%{cfg.buildcfg}"

project "DemoApp"
  kind "ConsoleApp"
  files { "main.cc", "variables.aki" } -- include the aki files just as if they were cpp files
  includedirs { ".", "%{cfg.targetdir}" } -- include the targetdir as its where we dump the autogenerated aki
  -- Where to put the generated files
  akigendir "bin/akigen"
