// Copyright (C) The (still) SANE Authors/Vincent Hengel 2023

// #include <cc_version.h>

#include "c_code_gen.h"

#include <base/hashing/fnv1a.h>
#include <base/strings/string_compare.h>

#include "../version.h"
#include "base/compiler.h"
#include "base/knob.h"
#include "base/logging.h"
#include "base/strings/string_ref.h"
#include "base/strings/xstring.h"

namespace feature_flags {
base::Knob<bool> MangleTranslatedSymbols{false};
base::Knob<bool> EmitCompilerSpecificTypes{false};
base::Knob<bool> EmitAutoGenHeader{true};
}  // namespace feature_flags

// version::kU8LanguageEdition

namespace insane {
using TS = TextPrinter::Substitution;

namespace {
constexpr char kTag[] = "ccodegen";

// TODO: also consider the length limits of some target compilers here in the
// future.
//   // Note that since we are in c mode, we cannot emit namespaces directly.
//   instead we
// prefix every symbol with a unique, deterministic, ID

base::StringU8 CreateUniqueSymbolName(const base::StringRefU8 namespace_name,
                                      const base::StringRefU8 symbol_name) {
  if (!feature_flags::MangleTranslatedSymbols)
    return base::MakeStringCopy(symbol_name);

  if (namespace_name != u8"$$$GLOBAL$$$") {
  }
  base::StringU8 name(base::MakeStringCopy(namespace_name));
  name.erase(std::remove(name.begin(), name.end(), u8'\0'), name.end());
  name += u8"_";
  auto fuckThis = std::to_string(
      base::FNV1a64(reinterpret_cast<const char*>(symbol_name.data())));
  name += (const char8_t*)fuckThis.c_str();
  name += u8"_";
  name += base::MakeStringCopy(symbol_name);
  return name;
}

// for f128 we need to optionally define a symbol custom
base::StringU8 ResolveTypeBit(const base::StringU8& type_core) {
  // fp exit
  if (type_core.length() < 2 && type_core.length() > 4) {
    return u8"auto";
  }
  // todo: we really ought to emit compiler specic core types here.
  base::StringU8 str;
  switch (type_core.c_str()[0]) {
    case 'f':
      if (type_core.c_str()[1] == '3' && type_core.c_str()[2] == '2') {
        str = u8"float";
      } else if (type_core.c_str()[1] == '6' && type_core.c_str()[2] == '4') {
        str = u8"double";
      }
      break;
    case 'i':
      if (type_core.c_str()[1] == '8') {
        str = u8"int8_t";
      } else if (type_core.c_str()[1] == '1' && type_core.c_str()[2] == '6') {
        str = u8"int16_t";
      } else if (type_core.c_str()[1] == '3' && type_core.c_str()[2] == '2') {
        str = u8"int32_t";
      } else if (type_core.c_str()[1] == '6' && type_core.c_str()[2] == '4') {
        str = u8"int64_t";
      }
      break;
    case 'u':
      if (type_core.c_str()[1] == '8') {
        str = u8"uint8_t";
      } else if (type_core.c_str()[1] == '1' && type_core.c_str()[2] == '6') {
        str = u8"uint16_t";
      } else if (type_core.c_str()[1] == '3' && type_core.c_str()[2] == '2') {
        str = u8"uint32_t";
      } else if (type_core.c_str()[1] == '6' && type_core.c_str()[2] == '4') {
        str = u8"uint64_t";
      }
      break;
    case 'c':
      if (type_core.c_str()[1] == '8') {
        str = u8"char";
      } else if (type_core.c_str()[1] == '1' && type_core.c_str()[2] == '6') {
        str = u8"uint16_t";
      } else if (type_core.c_str()[1] == '3' && type_core.c_str()[2] == '2') {
        str = u8"uint32_t";
      }
      break;
    case 'b':
      if (type_core[0] == 'b' && type_core[1] == 'o' && type_core[2] == 'o' &&
          type_core[3] == 'l') {
        str = u8"char";
      }
      break;
  }

  return str.empty() ? u8"auto" : str;
}
}  // namespace

// all compiler comments are appended with the //f syntax. this is to allow easy
// linting of fusion specifics.
constexpr char8_t kGeneratedFileHeader[] =
    u8"//f This file was auto-generated by aki cctranspiler "
    u8"$transpiler_version$ "
    u8"(C-Mode)\n//f Language edition: $language_edition$\n//f Do not edit.\n";

constexpr char8_t kEntryCode[] =
    u8"int main(int argc, char** argv)\n{\n  $entry_sub$(argc);\n  return "
    u8"0;\n}\n";

CCodeGen::CCodeGen() : printer_(buffer_) {}

void CCodeGen::CreateEntrypoint() {
  using TS = TextPrinter::Substitution;
  printer_.Print(kEntryCode, TS{u8"entry_sub", entry_symbol_});
}

void CCodeGen::EmitImport(const ParsedImport& import) {
  // TODO: substitute .fu for .h
  printer_.Print(u8"#include \"$file_name$\";\n",
                 TS{u8"file_name", import.target});
}

void CCodeGen::EmitVariable(const TranslationUnit& unit,
                            const ParsedVariableDecl& decl,
                            const base::StringRefU8 namespace_name,
                            const bool needs_mangeling) {
  const base::StringU8 variable_name =
      needs_mangeling ? CreateUniqueSymbolName(namespace_name, decl.name)
                      : base::MakeStringCopy(decl.name);

  const ParsedType* variable_type = translation_unit_->all_types.Get(decl.type);
  if (!variable_type) {
    BASE_LOGE(kTag, "Failed to find type for variable decl for {}",
              (char*)variable_name.c_str());
    return;
  }

  const ParsedExpression* assignment = nullptr;
  const ParsedOp* operation = nullptr;
  if (decl.optional_assignment != obj_handle(-1)) {
    assignment = unit.all_expressions.Get(decl.optional_assignment);
    if (!assignment) DEBUG_TRAP;
    operation = unit.all_ops.Get(*assignment->stack.at(0));
  }

  base::StringU8 type_core = base::MakeStringCopy(variable_type->data);
  base::StringU8 c_type = ResolveTypeBit(type_core);

  printer_.Print(
      u8"$is_hidden$$is_const$$type_decl$$is_pointed$$variable_name$",
      TS{u8"is_hidden",
         decl.visibility == Visibility::Private ? u8"static " : u8" "},
      TS{u8"is_const", decl.is_const ? u8"const " : u8" "},
      TS{u8"is_pointed",
         operation
             ? (operation->flags & ParsedOp::Flags::IsPointer ? u8" *" : u8" ")
             : u8" "},
      TS{u8"type_decl", c_type}, TS{u8"variable_name", variable_name});

  if (assignment && operation) {
    switch (operation->type) {
      case ParsedOp::Type::FunctionCall: {
        // TODO: emit params
        printer_.Print(u8" = $assignment$()",
                       TS{u8"assignment", operation->data});
        break;
      }
      default: {
        printer_.Print(u8" = $assignment$",
                       TS{u8"assignment", operation->data});
        break;
      }
    }
  }
  printer_.RawWrite(u8";\n");
}

void CCodeGen::EmitFunctionBlock(const TU& tu, const TU::Scope& scope,
                                 const ParsedFunctionDecl& fn,
                                 const base::StringRefU8 namespace_n) {
#if 1
  for (const TU::Scope::BigHandle biggie : scope.tree) {
    switch (biggie.type) {
      case TU::ObjectType::Variable: {
        const ParsedVariableDecl* variable =
            tu.all_variables.Get(biggie.handle);
        EmitVariable(tu, *variable, scope.name, /*needs_mangeling=*/false);
        break;
      }
      case TU::ObjectType::Statement: {
        const ParsedStatement* stmt = tu.all_statements.Get(biggie.handle);
        switch (stmt->type) {
          case ParsedStatement::Type::Return: {
            printer_.Print(u8"return");
#if 1
            const ParsedExpression* expr =
                tu.all_expressions.Get(*stmt->expr_stack.at(0));
            for (const ParsedOpRef op_ref : expr->stack) {
              const ParsedOp* op = tu.all_ops.Get(op_ref);
              printer_.Print(u8"$op$", TS{u8"op", op->data});
            }
#endif
            // printer_.Print(u8"return $expr$;\n", TS{u8"expr", expr->data});
            printer_.RawWrite(u8";\n");
            break;
          }
          case ParsedStatement::Type::Expression: {
            for (const ParsedExpressionRef h : stmt->expr_stack) {
              const ParsedExpression* expr = tu.all_expressions.Get(h);
              for (const ParsedOpRef op_ref : expr->stack) {
                const ParsedOp* op = tu.all_ops.Get(op_ref);
                printer_.Print(u8"$op$", TS{u8"op", op->data});
              }
              // printer_.Print(u8"$expr$", TS{u8"expr", expr->data});
            }
            printer_.RawWrite(u8";\n");
            break;
          }
        }
        break;
      }
    }
  }
#endif
}

void CCodeGen::EmitFunction(const ParsedFunctionDecl& decl,
                            const base::StringRefU8 namespace_name) {
  // create a unique name
  const auto mangled_name = CreateUniqueSymbolName(namespace_name, decl.name);

  const ParsedType* return_type =
      translation_unit_->all_types.Get(decl.return_type);

  // BUGCHECK(return_type, "Failed to find type for function return decl.");
  const auto return_type_val = return_type ? return_type->data : u8"void";

  base::StringU8 params;
  for (const ParsedParameterDeclRef h : decl.param_refs) {
    const ParsedParameterDecl* param = translation_unit_->all_parameters.Get(h);
    if (param->variable.is_const) params += u8"const ";
    const ParsedType* var_type =
        translation_unit_->all_types.Get(param->variable.type);
    BUGCHECK(var_type, "Failed to find type for function parameter decl.");
    params += base::MakeStringCopy(var_type->data, true);
    params += u8" ";
    params += base::MakeStringCopy(param->variable.name);
  }

  if (params.empty()) params = u8"void";

  printer_.Print(u8"$return_type$ $name$($params$);",
                 TS{u8"return_type", return_type_val},
                 TS{u8"name", mangled_name}, TS{u8"params", params});

  printer_.RawWrite(u8"\n");

  // test for attached scope:
  if (const auto* scope = translation_unit_->FindAttachedScope(decl.name)) {
    // BASE_LOGI(kTag,"Found attached scope: {}", decl.name);
    printer_.RawWrite(u8"{\n");

    printer_.PushIndent();
    printer_.Print(u8"//f fn scope: $name$\n", TS{u8"name", decl.name});
    EmitFunctionBlock(*translation_unit_, *scope, decl, namespace_name);
    // EmitScope(*scope, *translation_unit_);
    printer_.PopIndent();
    printer_.RawWrite(u8"}\n");
  }

  // do this because BASE is too stupid to handle it..
  if (base::Strcmp(decl.name.data(), u8"main", 4) == 0) {
    entry_symbol_ = mangled_name;
  }
}

void CCodeGen::EmitStruct(const ParsedComplexDecl& decl,
                          const base::StringRefU8 namespace_name) {
  // create a unique name
  const auto mangled_name = CreateUniqueSymbolName(namespace_name, decl.name);

  printer_.Print(u8"struct $name$;", TS{u8"name", mangled_name});
}

void CCodeGen::EmitEnum(const ParsedEnumDecl& decl,
                        const base::StringRefU8 namespace_name) {
  // create a unique name
  const auto mangled_name = CreateUniqueSymbolName(namespace_name, decl.name);
  printer_.Print(u8"enum $name$;", TS{u8"name", mangled_name});
  printer_.Print(u8" {\n");
  for (const base::StringRefU8& member : decl.member_values) {
    printer_.Print(u8"  $member$,\n", TS{u8"member", member});
  }
  printer_.Print(u8"};\n");
}

void CCodeGen::EmitScope(const TranslationUnit::Scope& scope,
                         const TranslationUnit& tu) {
  // if the scope itself is a namespace, we emit a comment
  if (scope.type == TranslationUnit::Scope::Type::Namespace) {
    printer_.Print(u8"//f Beginning namespace: $name$\n",
                   TS{u8"name", scope.name});
  }
  if (scope.type == TranslationUnit::Scope::Type::Complex) {
    printer_.Print(u8"//f Beginning class: $name$\n", TS{u8"name", scope.name});
  }
  for (const ParsedImportRef h : scope.imports) {
    const ParsedImport* import = tu.all_imports.Get(h);
    EmitImport(*import);
  }
  for (const ParsedNamespaceRef h : scope.namespaces) {
    const ParsedNamespace* ns = tu.all_namespaces.Get(h);
    if (const TranslationUnit::Scope* sub_scope =
            tu.FindAttachedScope(ns->name))
      EmitScope(*sub_scope, tu);
    else
      DEBUG_TRAP;
    // BASE_LOGE(kTag,"Failed to find attached scope for namespace: {}",
    // ns->name);
  }
  for (const ParsedEnumDeclRef h : scope.enums) {
    const ParsedEnumDecl* enumd = tu.all_enums.Get(h);
    EmitEnum(*enumd, scope.name);
  }
  for (const ParsedVariableDeclRef h : scope.global_variables) {
    const ParsedVariableDecl* variable = tu.all_variables.Get(h);
    EmitVariable(tu, *variable, scope.name);
  }
  for (const ParsedFunctionDeclRef h : scope.functions) {
    const ParsedFunctionDecl* fn = tu.all_functions.Get(h);
    EmitFunction(*fn, scope.name);
  }
  for (const ParsedComplexDeclRef h : scope.complexes) {
    const ParsedComplexDecl* structd = tu.all_complexes.Get(h);
    EmitStruct(*structd, scope.name);
  }
}

void CCodeGen::GenerateCode(TranslationUnit& unit) {
  translation_unit_ = &unit;

  if (feature_flags::EmitAutoGenHeader) {
    printer_.Print(kGeneratedFileHeader,
                   TS{u8"transpiler_version", version::kTranspilerVersion},
                   TS{u8"language_edition", version::kU8LanguageEdition});
  }

  BASE_LOGI(kTag, "Generating global TU.");
  EmitScope(*unit.global_scope(),
            unit);  // this is not really a namespace but a shared space

  // if this translation unit contained a fusion main, it becomes our c main
  // file, thus we generate a call from the real c main to the fusion main and
  // set up the parameters accordingly
  if (!entry_symbol_.empty()) {
    CreateEntrypoint();
  }
}
}  // namespace insane
